source 'http://rubygems.org'

gem 'adsf'
gem 'builder'
gem 'compass'
gem 'json'
gem 'fssm'
gem 'nanoc3', :git => 'https://github.com/ddfreyne/nanoc.git'
gem 'rack'
gem 'rake'
gem 'rb-fsevent'
gem 'w3c_validators'
